export const FETCH_NEWS_START = 'FETCH_NEWS_INIT';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const FETCH_NEWS_ITEM_START= 'FETCH_NEWS_ITEM_START';
export const  FETCH_NEWS_ITEM_SUCCESS= 'FETCH_NEWS_ITEM_SUCCESS';
export const FETCH_NEWS_ITEM_FAIL= 'FETCH_NEWS_ITEM_FAIL';
